import { Sparkles } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export function AiDraftBanner() {
  return (
    <Alert className="border-accent bg-accent/40">
      <Sparkles />
      <AlertTitle>AI Draft — Practitioner Review Required</AlertTitle>
      <AlertDescription>
        This plan was generated by AI and has not been reviewed. Check every meal, ingredient, and nutrition
        total before moving it to review or sharing it with the patient.
      </AlertDescription>
    </Alert>
  );
}
